// These styles apply to every route in the application
import Footer from './components/Home/Footer'
import Header from './components/Home/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body>
    <Header /> {/* Your header component */}
    <main>{children}</main> {/* Main content */}
    <Footer /> {/* Footer should be inside body */}
  </body>
    </html>
  )
}